# Generated by Django 3.2.14 on 2023-08-12 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230812_0417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mastercategory',
            options={'verbose_name_plural': ' Master categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='master_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='products.mastercategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category'),
        ),
    ]
