# Generated by Django 3.2.14 on 2023-08-12 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='mastercategory',
            options={'verbose_name_plural': 'Master categories'},
        ),
    ]
