# Generated by Django 3.2.14 on 2023-08-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_auto_20230812_1428"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="part_number",
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.FileField(null=True, upload_to="product_images/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Name / Part Number"),
        ),
    ]
