# Generated by Django 3.2.14 on 2023-09-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_requests', '0002_auto_20230906_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
    ]
