# Generated by Django 3.2.14 on 2023-09-06 11:57

from django.db import migrations, models
import quote_requests.validators


class Migration(migrations.Migration):

    dependencies = [
        ('quote_requests', '0004_alter_requestedproduct_quote_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[quote_requests.validators.validate_requested_product_quantity]),
        ),
    ]
