# Generated by Django 4.2.5 on 2023-10-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quote_requests", "0006_alter_quoterequest_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quoterequest",
            name="company_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
